"""net worth snapshots

Revision ID: f697a9b0e832
Revises: dd209d9e6f02
Create Date: 2026-08-03 08:43:06.078312

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f697a9b0e832"
down_revision: str | None = "dd209d9e6f02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "net_worth_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("assets", sa.BigInteger(), nullable=False),
        sa.Column("liabilities", sa.BigInteger(), nullable=False),
        sa.Column("net_worth", sa.BigInteger(), nullable=False),
        sa.Column("cash", sa.BigInteger(), nullable=False),
        sa.Column("investments", sa.BigInteger(), nullable=False),
        sa.Column("credit", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_net_worth_snapshot_user_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("net_worth_snapshots")
    # ### end Alembic commands ###
