"""rules and transaction search

Revision ID: 38bfed0a50a5
Revises: 2b6f77787ea3
Create Date: 2026-08-02 18:56:24.754477

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "38bfed0a50a5"
down_revision: str | None = "2b6f77787ea3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rules_user_priority", "rules", ["user_id", "priority"])
    # ### end Alembic commands ###

    # Hand-written: autogenerate cannot detect expression indexes.
    #
    # GIN over the same expression the query builds, so the planner can actually
    # use it. Two details matter:
    #   - 'english'::regconfig, not 'english'. The text form resolves the config
    #     at runtime, making to_tsvector STABLE rather than IMMUTABLE, which
    #     Postgres refuses to index.
    #   - The expression must match _search_predicate in transaction_service
    #     exactly, or the index is silently ignored and search seq-scans.
    op.execute(
        """
        CREATE INDEX ix_transactions_search
        ON transactions
        USING GIN (
            to_tsvector(
                'english'::regconfig,
                coalesce(name, '') || ' ' ||
                coalesce(merchant_name, '') || ' ' ||
                coalesce(notes, '')
            )
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_transactions_search")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rules_user_priority", table_name="rules")
    op.drop_table("rules")
    # ### end Alembic commands ###
