"""plaid items and sync runs

Revision ID: dd209d9e6f02
Revises: 38bfed0a50a5
Create Date: 2026-08-02 22:17:51.413546

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dd209d9e6f02"
down_revision: str | None = "38bfed0a50a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plaid_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("plaid_item_id", sa.Text(), nullable=False),
        sa.Column("plaid_institution_id", sa.Text(), nullable=True),
        sa.Column("institution_name", sa.Text(), nullable=True),
        sa.Column("institution_logo_url", sa.Text(), nullable=True),
        sa.Column("access_token_encrypted", sa.Text(), nullable=False),
        sa.Column("transactions_cursor", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), server_default="good", nullable=False),
        sa.Column("last_successful_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=60), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("consent_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plaid_item_id"),
    )
    op.create_index("ix_plaid_items_user", "plaid_items", ["user_id", "status"], unique=False)
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("plaid_item_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="running", nullable=False),
        sa.Column("added", sa.Integer(), nullable=False),
        sa.Column("modified", sa.Integer(), nullable=False),
        sa.Column("removed", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["plaid_item_id"], ["plaid_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sync_runs_user_started", "sync_runs", ["user_id", "started_at"], unique=False
    )
    op.add_column("accounts", sa.Column("plaid_item_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "accounts", "plaid_items", ["plaid_item_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.drop_column("accounts", "plaid_item_id")
    op.drop_index("ix_sync_runs_user_started", table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_index("ix_plaid_items_user", table_name="plaid_items")
    op.drop_table("plaid_items")
    # ### end Alembic commands ###
