"""accounts categories transactions

Revision ID: 2b6f77787ea3
Revises: 0001
Create Date: 2026-08-02 18:05:04.985939

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2b6f77787ea3"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("plaid_account_id", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("official_name", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("subtype", sa.String(length=40), nullable=True),
        sa.Column("mask", sa.String(length=8), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), server_default="USD", nullable=False),
        sa.Column("balance_current", sa.BigInteger(), nullable=False),
        sa.Column("balance_available", sa.BigInteger(), nullable=True),
        sa.Column("balance_limit", sa.BigInteger(), nullable=True),
        sa.Column("is_manual", sa.Boolean(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("include_in_net_worth", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plaid_account_id"),
    )
    op.create_index("ix_accounts_user_active", "accounts", ["user_id", "deleted_at"], unique=False)
    op.create_index("ix_accounts_user_type", "accounts", ["user_id", "type"], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("kind", sa.String(length=10), server_default="expense", nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "slug", name="uq_category_user_slug"),
    )
    op.create_table(
        "account_balance_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("balance_current", sa.BigInteger(), nullable=False),
        sa.Column("balance_available", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "date", name="uq_balance_snapshot_account_date"),
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("default_category_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["default_category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "normalized_name", name="uq_merchant_user_normalized"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("plaid_transaction_id", sa.Text(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), server_default="USD", nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("authorized_date", sa.Date(), nullable=True),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("merchant_name", sa.Text(), nullable=True),
        sa.Column("merchant_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("category_source", sa.String(length=10), nullable=True),
        sa.Column("plaid_pfc_primary", sa.String(length=60), nullable=True),
        sa.Column("plaid_pfc_detailed", sa.String(length=80), nullable=True),
        sa.Column("pending", sa.Boolean(), nullable=False),
        sa.Column("pending_plaid_transaction_id", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_manual", sa.Boolean(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("exclude_from_budget", sa.Boolean(), nullable=False),
        sa.Column("is_split", sa.Boolean(), nullable=False),
        sa.Column("parent_transaction_id", sa.UUID(), nullable=True),
        sa.Column("is_transfer", sa.Boolean(), nullable=False),
        sa.Column("transfer_group_id", sa.UUID(), nullable=True),
        sa.Column("location_city", sa.Text(), nullable=True),
        sa.Column("location_region", sa.String(length=60), nullable=True),
        sa.Column("payment_channel", sa.String(length=30), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plaid_transaction_id"),
    )
    op.create_index(
        "ix_transactions_account_date",
        "transactions",
        ["account_id", sa.literal_column("date DESC")],
        unique=False,
    )
    op.create_index(
        "ix_transactions_parent", "transactions", ["parent_transaction_id"], unique=False
    )
    op.create_index(
        "ix_transactions_transfer_group",
        "transactions",
        ["user_id", "transfer_group_id"],
        unique=False,
        postgresql_where=sa.text("transfer_group_id IS NOT NULL"),
    )
    op.create_index(
        "ix_transactions_user_category_date",
        "transactions",
        ["user_id", "category_id", "date"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_date",
        "transactions",
        ["user_id", sa.literal_column("date DESC")],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_date_active",
        "transactions",
        ["user_id", sa.literal_column("date DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_split = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_transactions_user_date_active",
        table_name="transactions",
        postgresql_where=sa.text("deleted_at IS NULL AND is_split = false"),
    )
    op.drop_index("ix_transactions_user_date", table_name="transactions")
    op.drop_index("ix_transactions_user_category_date", table_name="transactions")
    op.drop_index(
        "ix_transactions_transfer_group",
        table_name="transactions",
        postgresql_where=sa.text("transfer_group_id IS NOT NULL"),
    )
    op.drop_index("ix_transactions_parent", table_name="transactions")
    op.drop_index("ix_transactions_account_date", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("merchants")
    op.drop_table("account_balance_snapshots")
    op.drop_table("categories")
    op.drop_index("ix_accounts_user_type", table_name="accounts")
    op.drop_index("ix_accounts_user_active", table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
