"""investments

Revision ID: 9c780e0034f7
Revises: 65666f94c4ef
Create Date: 2026-08-03 09:38:32.635734

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9c780e0034f7"
down_revision: str | None = "65666f94c4ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "securities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plaid_security_id", sa.Text(), nullable=True),
        sa.Column("ticker", sa.String(length=24), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=True),
        sa.Column("cusip", sa.String(length=12), nullable=True),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("close_price", sa.BigInteger(), nullable=True),
        sa.Column("close_price_as_of", sa.Date(), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), server_default="USD", nullable=False),
        sa.Column("is_cash_equivalent", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plaid_security_id"),
    )
    op.create_table(
        "holding_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_value", sa.BigInteger(), nullable=False),
        sa.Column("total_cost_basis", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "date", name="uq_holding_snapshot_account_date"),
    )
    op.create_table(
        "holdings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cost_basis", sa.BigInteger(), nullable=True),
        sa.Column("institution_price", sa.BigInteger(), nullable=True),
        sa.Column("institution_value", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), server_default="USD", nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["security_id"], ["securities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "security_id", name="uq_holding_account_security"),
    )
    op.create_index("ix_holdings_user", "holdings", ["user_id"], unique=False)
    op.create_table(
        "investment_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.UUID(), nullable=True),
        sa.Column("plaid_investment_transaction_id", sa.Text(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=True),
        sa.Column("subtype", sa.String(length=40), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("price", sa.BigInteger(), nullable=True),
        sa.Column("fees", sa.BigInteger(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), server_default="USD", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["security_id"], ["securities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plaid_investment_transaction_id"),
    )
    op.create_index(
        "ix_inv_txn_user_date", "investment_transactions", ["user_id", "date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inv_txn_user_date", table_name="investment_transactions")
    op.drop_table("investment_transactions")
    op.drop_index("ix_holdings_user", table_name="holdings")
    op.drop_table("holdings")
    op.drop_table("holding_snapshots")
    op.drop_table("securities")
    # ### end Alembic commands ###
