"""audit log and preferences

Revision ID: 2096cacf6b54
Revises: 9c780e0034f7
Create Date: 2026-08-03 09:55:54.776874

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2096cacf6b54"
down_revision: str | None = "9c780e0034f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ---- Better Auth two-factor schema -------------------------------------
    # Hand-written: these are owned by Better Auth, not modelled in SQLAlchemy,
    # so autogenerate cannot see them. Must stay in sync with the twoFactor
    # plugin config in apps/web/src/lib/auth.ts.
    op.add_column(
        "user",
        sa.Column(
            "twoFactorEnabled",
            sa.Boolean(),
            nullable=True,
            server_default=sa.text("false"),
        ),
    )
    op.create_table(
        "twoFactor",
        sa.Column("id", sa.Text(), nullable=False),
        # secret and backupCodes are encrypted by Better Auth using
        # BETTER_AUTH_SECRET before they reach these columns.
        sa.Column("secret", sa.Text(), nullable=False),
        sa.Column("backupCodes", sa.Text(), nullable=False),
        sa.Column("userId", sa.Text(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=True, server_default=sa.text("true")),
        sa.Column(
            "failedVerificationCount",
            sa.Integer(),
            nullable=True,
            server_default=sa.text("0"),
        ),
        sa.Column("lockedUntil", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["userId"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_twoFactor_userId", "twoFactor", ["userId"])
    op.create_index("ix_twoFactor_secret", "twoFactor", ["secret"])

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_user_created", "audit_log", ["user_id", "created_at"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), server_default="USD", nullable=False),
        sa.Column("theme", sa.String(length=10), server_default="system", nullable=False),
        sa.Column("week_starts_on", sa.Integer(), server_default="0", nullable=False),
        sa.Column("timezone", sa.String(length=60), server_default="UTC", nullable=False),
        sa.Column("hide_from_dashboard", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_twoFactor_secret", table_name="twoFactor")
    op.drop_index("ix_twoFactor_userId", table_name="twoFactor")
    op.drop_table("twoFactor")
    op.drop_column("user", "twoFactorEnabled")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_preferences")
    op.drop_index("ix_audit_user_created", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
